version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-peer-review-app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./Laravel:/var/www/html/Laravel
      - ./Laravel/storage:/var/www/html/Laravel/storage
      - ./Laravel/database:/var/www/html/Laravel/database
    environment:
      - APP_NAME=Student Peer Review
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/Laravel/database/database.sqlite
    depends_on:
      - redis
    networks:
      - student-review-network

  # Redis for caching and sessions (optional but recommended)
  redis:
    image: redis:7-alpine
    container_name: student-peer-review-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - student-review-network

  nginx:
    image: nginx:alpine
    container_name: student-peer-review-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Laravel:/var/www/html/Laravel:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/sites-available:/etc/nginx/sites-available:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - student-review-network
    profiles:
      - nginx

volumes:
  redis_data:
    driver: local

networks:
  student-review-network:
    driver: bridge 