version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-peer-review-app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./Laravel:/var/www/html/Laravel
      - ./Laravel/storage:/var/www/html/Laravel/storage
      - ./Laravel/database:/var/www/html/Laravel/database
    environment:
      - APP_NAME=Student Peer Review
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/Laravel/database/database.sqlite
    depends_on:
      - redis
    networks:
      - student-review-network

  # Redis for caching and sessions (optional but recommended)
  redis:
    image: redis:7-alpine
    container_name: student-peer-review-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - student-review-network

  # MySQL Database (alternative to SQLite for production)
  mysql:
    image: mysql:8.0
    container_name: student-peer-review-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: student_peer_review
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - student-review-network

  # Nginx (alternative web server)
  nginx:
    image: nginx:alpine
    container_name: student-peer-review-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Laravel:/var/www/html/Laravel:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/sites-available:/etc/nginx/sites-available:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - student-review-network
    profiles:
      - nginx

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: student-peer-review-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - student-review-network
    profiles:
      - database-admin

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  student-review-network:
    driver: bridge 